name = "test-selector"
main = "src/index.ts"
compatibility_date = "2024-04-07"

[env.production]
routes = [
  { pattern = "www.jacobmacmillan.digital", custom_domain = true },
  { pattern = "jacobmacmillan.digital", custom_domain = true },
]

[[r2_buckets]]
binding = 'SITE_BUCKET'
bucket_name = 'jms-site-experiments'
preview_bucket_name = 'jms-site-experiments'
