name = "test-selector"
main = "src/index.ts"
compatibility_date = "2024-04-07"

[[r2_buckets]]
binding = 'SITE_BUCKET'
bucket_name = 'jms-site-experiments'
preview_bucket_name = 'jms-site-experiments'
